language: de

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
pipeline:
  - name: SpacyNLP
    model: "de_core_news_sm"
    case_sensitive: False
  - name: components.LanguageDetection.MyComponent
  - name: SpacyTokenizer
  - name: components.SentimentAnalysis.MyComponent
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["time", "phone-number", "email"]
    locale: "de_DE"
    timezone: "Europe/Berlin"
    timeout: 3
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    "use_word_boundaries": True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    model_confidence: "linear_norm"
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
